# Generated by Django 4.1.1 on 2022-09-28 13:04

import admission.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название экзамена')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
            },
        ),
        migrations.CreateModel(
            name='ProfileClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('first_profile_exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_profile_exam_for_profile_class', to='admission.exam', verbose_name='Профильный экзамен № 1')),
                ('second_profile_exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_profile_exam_for_profile_class', to='admission.exam', verbose_name='Профильный экзамен № 2')),
            ],
            options={
                'verbose_name': 'Профильный класс',
                'verbose_name_plural': 'Профильные классы',
            },
        ),
        migrations.CreateModel(
            name='EnrollApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес места жительства')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Контактный телефон')),
                ('email', models.CharField(blank=True, max_length=300, verbose_name='Контактный адрес электронной почты')),
                ('passport_seria', models.PositiveIntegerField(verbose_name='Серия паспорта')),
                ('passport_number', models.PositiveIntegerField(verbose_name='Номер паспорта')),
                ('father_fio', models.CharField(max_length=300, verbose_name='ФИО отца')),
                ('father_phone', models.CharField(max_length=100, verbose_name='Контактный телефон отца')),
                ('father_address', models.CharField(max_length=500, verbose_name='Адрес места жительства отца')),
                ('mothers_fio', models.CharField(max_length=300, verbose_name='ФИО матери')),
                ('mothers_phone', models.CharField(max_length=100, verbose_name='Контактный телефон матери')),
                ('mothers_address', models.CharField(max_length=500, verbose_name='Адрес места жительства матери')),
                ('certificate_average_score', models.FloatField(verbose_name='Средний балл аттестата')),
                ('russian_exam_point', models.PositiveIntegerField(verbose_name='Баллы за экзамен по русскому языку')),
                ('math_exam_point', models.PositiveIntegerField(verbose_name='Баллы за экзамен по математике')),
                ('first_profile_exam_point', models.PositiveIntegerField(verbose_name='Баллы за экзамен по выбору № 1')),
                ('second_profile_exam_point', models.PositiveIntegerField(verbose_name='Баллы за экзамен по выбору № 2')),
                ('passport_file', models.FileField(upload_to='passport/', verbose_name='Паспорт')),
                ('certificate_file', models.FileField(upload_to='certificate/', verbose_name='Аттестат')),
                ('marks_file', models.FileField(upload_to='marks/', verbose_name='Оценки')),
                ('exams_file', models.FileField(upload_to='exams/', verbose_name='Результаты ОГЭ')),
                ('is_accepted', models.BooleanField(default=False, validators=[admission.validators.validate_is_true], verbose_name='Согласие на обработку данных')),
                ('notification_method', models.CharField(choices=[('phone', 'По номеру телефона'), ('email', 'На электронную почту')], max_length=100, verbose_name='Метод оповещения о результатах')),
                ('status', models.CharField(choices=[('verification', 'В процессе верификации'), ('process', 'В процессе обработки'), ('results', 'Есть результаты отбора')], default='verification', help_text='Заполняется администрацией', max_length=100, verbose_name='Статус заявки')),
                ('rating_place', models.IntegerField(default=-1, help_text='Заполняется администрацией', verbose_name='Место в общем рейтинге')),
                ('first_profile_exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_profile_exam', to='admission.exam', verbose_name='Экзамен по выбору № 1')),
                ('profile_class', models.ManyToManyField(to='admission.profileclass', verbose_name='Профильные классы')),
                ('second_profile_exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_profile_exam', to='admission.exam', verbose_name='Экзамен по выбору № 2')),
            ],
            options={
                'verbose_name': 'Заявление на поступление в лицей',
                'verbose_name_plural': 'Заявления на поступление в лицей',
            },
        ),
    ]
