# Generated by Django 4.1.1 on 2022-09-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollapplication',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата подачи заявки'),
        ),
    ]
