# Generated by Django 4.1.1 on 2023-02-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=300, verbose_name='Название профильного класса')),
                ('number_of_received', models.PositiveIntegerField(verbose_name='Количество поступивших')),
                ('number_of_graduates', models.PositiveIntegerField(verbose_name='Количество выпустившихся')),
                ('number_of_medalists', models.PositiveIntegerField(verbose_name='Количество выпустившихся медалистов')),
                ('number_of_state_employees', models.PositiveIntegerField(verbose_name='Количество выпустившихся бюджетников')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистики',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(help_text='В формате: "Фамилия И.О."', max_length=300, verbose_name='ФИО учителя')),
                ('photo', models.ImageField(upload_to='teachers/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.AlterField(
            model_name='enrollapplication',
            name='father_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактный номер телефона отца'),
        ),
        migrations.AlterField(
            model_name='enrollapplication',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактный номер телефона матери'),
        ),
        migrations.AlterField(
            model_name='enrollapplication',
            name='phone',
            field=models.CharField(max_length=100, unique=True, verbose_name='Контактный номер телефона'),
        ),
        migrations.AlterField(
            model_name='enrollapplication',
            name='profile_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.profileclass', verbose_name='Профильный класс'),
        ),
        migrations.AlterField(
            model_name='enrollapplication',
            name='rating_place',
            field=models.FloatField(default=-1, help_text='Заполняется администрацией', verbose_name='Рейтинг'),
        ),
    ]
