# Generated by Django 4.1.1 on 2023-02-07 15:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_statistic_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileclass',
            name='color',
            field=colorfield.fields.ColorField(default='#d9d9d9', image_field=None, max_length=18, samples=None, verbose_name='Цвет карточки на сайте'),
        ),
    ]
