# Generated by Django 4.1.1 on 2023-02-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_profileclass_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='lesson',
            field=models.CharField(default='ОБЖ', max_length=300, verbose_name='Предмет'),
            preserve_default=False,
        ),
    ]
