# Generated by Django 4.1.1 on 2023-02-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_teacher_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='class_name',
            new_name='name',
        ),
    ]
