# Generated by Django 4.1.1 on 2023-04-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_rename_class_name_statistic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileclass',
            name='competitive_places',
            field=models.PositiveIntegerField(default=30, verbose_name='Количество мест'),
            preserve_default=False,
        ),
    ]
