# Generated by Django 4.1.1 on 2023-04-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_profileclass_competitive_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_make_applications', models.BooleanField(default=False, help_text='Если НЕТ, функицонал личного кабинета и формы поступления будет не доступен', verbose_name='Могут ли дети подавать заявки')),
            ],
            options={
                'verbose_name': 'Конфигурация',
                'verbose_name_plural': 'Конфигурация',
            },
        ),
        migrations.AlterField(
            model_name='enrollapplication',
            name='rating_place',
            field=models.FloatField(default=-1, help_text='Заполняется администрацией', verbose_name='Место в рейтинге'),
        ),
        migrations.AlterField(
            model_name='enrollapplication',
            name='status',
            field=models.CharField(choices=[('verification', 'В процессе верификации заявки'), ('processed', 'В процессе обработки заявки'), ('resolved', 'Определенно место в рейтинге'), ('successes', 'Вы приняты'), ('rejected', 'Вы не приняты')], default='verification', help_text='Заполняется администрацией', max_length=100, verbose_name='Статус заявки'),
        ),
    ]
