# Generated by Django 4.1.1 on 2023-04-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_alter_enrollapplication_rating_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='get_documents_date',
            field=models.DateField(help_text='Отображается в email-е', null=True, verbose_name='Дата приема документов, предварительно поступивших учеников'),
        ),
        migrations.AlterField(
            model_name='enrollapplication',
            name='status',
            field=models.CharField(choices=[('verification', 'В процессе верификации заявки'), ('processed', 'В процессе обработки заявки'), ('resolved', 'Определенно место в рейтинге'), ('success', 'Вы приняты'), ('rejected', 'Вы не приняты')], default='verification', help_text='Заполняется администрацией', max_length=100, verbose_name='Статус заявки'),
        ),
    ]
