# Generated by Django 4.1.1 on 2023-04-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_siteconfiguration_get_documents_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='conflict_commission_date',
            field=models.DateField(null=True, verbose_name='Дата сбора конфликтной комиссии'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='end_conflict_commission_time',
            field=models.TimeField(null=True, verbose_name='Время окончания конфликтной комисси'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='start_conflict_commission_time',
            field=models.TimeField(null=True, verbose_name='Время начала конфликтной комисси'),
        ),
    ]
