# Generated by Django 4.1.1 on 2023-04-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_siteconfiguration_conflict_commission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollapplication',
            name='rating_place',
            field=models.IntegerField(default=0, help_text='Заполняется администрацией', verbose_name='Место в рейтинге'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='conflict_commission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сбора конфликтной комиссии'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='end_conflict_commission_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания конфликтной комисси'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='get_documents_date',
            field=models.DateField(blank=True, help_text='Отображается в email-е', null=True, verbose_name='Дата приема документов, предварительно поступивших учеников'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='start_conflict_commission_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала конфликтной комисси'),
        ),
    ]
