# Generated by Django 4.1.1 on 2023-04-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_alter_enrollapplication_rating_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollapplication',
            name='rating_place',
            field=models.PositiveIntegerField(default=0, help_text='Заполняется администрацией', verbose_name='Место в рейтинге'),
        ),
    ]
